name: Docker CI 38

on: [push, pull_request]

jobs:

  build-test:
    name: Build docker and run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build the Docker image
        run: docker build . --file Dockerfile.38 --tag mapillary/opensfm.38:$GITHUB_SHA


      - name: Export whl to releases
        run: |
          mkdir -p wheel_output
          docker create --name temp_container mapillary/opensfm.38:$GITHUB_SHA
          docker cp temp_container:/source/OpenSfM/dist/. ./wheel_output/
          docker rm temp_container

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: opensfm-wheels
          path: ./wheel_output/

      # - name: Run C++ tests
      #   run: docker run mapillary/opensfm.38:$GITHUB_SHA /bin/sh -c "cd cmake_build && ctest"

      # - name: Run Python tests
      #   run: docker run mapillary/opensfm.38:$GITHUB_SHA python3 -m pytest
